#!/usr/bin/env python
from packager import Packager
import sys, os

def main(args):
    thisdir = os.path.dirname(os.path.realpath(__file__))
    #assume this script resides one dir below the fulfillment root
    rootdir = os.path.join(thisdir, "..")

    p = Packager(rootdir)
    p.package()

if __name__ == "__main__":
    main(sys.argv)
