#!/usr/bin/env python
splogger import Splogger
from launcher import Launcher
import sys, os
import argparse

def main():
    logfile="/var/log/balihoo/fulfillment/launcher.log"
    launcher = Launcher("fulfillment.jar", logfile)
    classes = arg.classes if len(arg.classes) > 0 else None
    launcher.launch(classes)

if __name__ == "__main__":
    main()
